name = "tlootbot"
main = "./src/server.js"
compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2025-02-14"

kv_namespaces = [
  { binding = "tlootbotkv", id = "a01385af75744f94aefa5b1945ecd5c9" }
]